kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: database
  name: mongo-pod-read
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongo-pod-read
  namespace: database
subjects:
- kind: ServiceAccount
  name: default
  namespace: database
roleRef:
  kind: Role
  name: mongo-pod-read
  apiGroup: rbac.authorization.k8s.io 